export const AUTHENTIFICATION_LOGGED_START = 'AUTHENTIFICATION_LOGGED_START';
export const AUTHENTIFICATION_LOGGED_SUCCESS = 'AUTHENTIFICATION_LOGGED_SUCCESS';
export const AUTHENTIFICATION_LOGGED_FAIL = 'AUTHENTIFICATION_LOGGED_FAIL';
export const AUTHENTIFICATION_LOGGED_OUT = 'AUTHENTIFICATION_LOGGED_OUT';
